name: Upload to Debian Repository
description: Upload a debian package to a debian repository using dput-ng
inputs:
  ssh-private-key:
    description: SSH private key for connecting via sftp
    required: true
  debian-repository:
    description: Domain of the Debian repository
    required: true
  working-directory:
    description: Working directory
    requiired: true
  changes-file:
    description: Name of the changes file
    required: true
runs:
  using: "composite"
  steps:
    - name: Register SSH Key with SSH Agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{inputs.ssh-private-key}}
    - name: Add dput-ng Config File
      shell: bash
      working-directory: ${{github.action_path}}
      run: sed "s/REPOSITORY/${{inputs.debian-repository}}/" dput.json > /etc/dput.d/profiles/upload-action.json
    - name: Add Debian Repository SSH Host Key to Known Hosts
      shell: bash
      run: ssh-keyscan ${{inputs.debian-repository}} >> /etc/ssh/ssh_known_hosts
    - name: Upload Debian Package to Repository
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: dput upload-action ${{inputs.changes-file}}
    - name: Process Remote Files
      shell: bash
      run: ssh "process@${{inputs.debian-repository}}"
